version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "0.0.0.0:8000:8000"
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: root
  #   ports:
  #     - 8081:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   volumes:
  #     - ~/jenkins:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
  api: null
